# Generated by Django 4.0.5 on 2022-06-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swoleapi', '0002_session_exercise_in_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_note',
            name='exercise_in_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='swoleapi.exercise_in_session'),
            preserve_default=False,
        ),
    ]
