# Generated by Django 4.0.5 on 2022-06-10 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swoleapi', '0003_exercise_note_exercise_in_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_in_session',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exercises_in_Session', to='swoleapi.session'),
        ),
    ]
