# Generated by Django 4.0.5 on 2022-06-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swoleapi', '0004_alter_exercise_in_session_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
