# Generated by Django 4.0.5 on 2022-06-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swoleapi', '0006_alter_session_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_in_session',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sessions', to='swoleapi.exercise'),
        ),
    ]
