# Generated by Django 4.0.5 on 2022-06-15 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swoleapi', '0007_alter_exercise_in_session_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_in_session',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 16, 4, 55, 681998)),
        ),
    ]
