# Generated by Django 4.0.5 on 2022-06-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swoleapi', '0008_exercise_in_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_in_session',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
