# Generated by Django 4.0.5 on 2022-06-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swoleapi', '0009_alter_exercise_in_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swole_user',
            name='profile_picture_url',
            field=models.CharField(default='http://s3.amazonaws.com/pix.iemoji.com/images/emoji/apple/ios-12/256/flexed-biceps.png', max_length=200),
        ),
    ]
