# Generated by Django 4.0.5 on 2022-06-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swoleapi', '0010_alter_swole_user_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swole_user',
            name='profile_picture_url',
            field=models.CharField(default='💪', max_length=200),
        ),
    ]
